{{- $Values := .Values -}}
{{- $ := . -}}
{{- range .Values.deployments}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .fullname }}
  
spec:
  {{- if not $Values.autoscaling.enabled }}
  replicas: {{ $Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
    {{- range .selectorLabels}} {{toYaml . | nindent 6}} {{- end }}
{{/*      {{- include "ts.selectorLabels" . | nindent 6 }}*/}}
  template:
    metadata:
      labels:
      {{- range .selectorLabels }} {{- toYaml . | nindent 8}} {{- end }}
    spec:
      {{- with $Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .fullname }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 10}}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8}}
      {{- end }}
{{/*      {{- with .Values.nodeSelector }}*/}}
{{/*      nodeSelector:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.affinity }}*/}}
{{/*      affinity:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.tolerations }}*/}}
{{/*      tolerations:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
---
{{- end}}
